[PM-7950] Build workflow should use the provided TEST_WEB_HOST env variable if available
bitwarden/test-the-web pull request #137
Opened 2024-05-06 15:10 UTC by jprusik

## 🎟️ Tracking

PM-7950

## 📔 Objective

Any environment variable consumed by docusaurus (with [a few exceptions](https://docusaurus.io/docs/advanced/ssg#node-env)) need to be available at build time

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-05-13 20:54 UTC, vgrassia requested changes

2024-05-13 20:54 UTC, vgrassia commented on .github/workflows/build.yml
>            npm run build
```suggestion
      - name: Clean install dependencies and build
        run: |
          npm ci
          export TEST_WEB_HOST="${{ secrets.TEST_WEB_HOST || 'https://localhost' }}"
          npm run build
```
```suggestion
      - name: Clean install dependencies and build
        env:
          TEST_WEB_HOST: "${{ secrets.TEST_WEB_HOST || 'https://localhost' }}"
        run: |
          npm ci
          npm run build
```

2024-05-14 14:31 UTC, jprusik commented on .github/workflows/build.yml
>            npm run build
thanks; tested and implemented in 47f011275b8650e55b375e1089ec6d6a7f9641a8

2024-05-14 14:31 UTC, vgrassia approved these changes

2024-05-14 14:31 UTC, merged